const ActionTypes = {
    ISLOADER: 'ISLOADER',
    ISERROR: 'ISERROR',
    CURRENTUSER: 'CURRENTUSER',
    FREEPOTATOES: 'FREEPOTATOES',
    TOPICLIST:'TOPICLIST',
    REVIEWS:'REVIEWS',
    GETREVIEWS:"GETREVIEWS",
    BLOCKCHAT:"BLOCKCHAT",
    FORGETPASS:"FORGETPASS",
    ALLCONVERSATION:"ALLCONVERSATION",
    SINGLEMSGS:"SINGLEMSGS",
}
export default ActionTypes;
